<a href="https://colab.research.google.com/github/harunbansode/Numpy00/blob/main/Numpy00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [149]:
import numpy as np

In [150]:
a = np.array([1, 2, 3])

In [151]:
a

array([1, 2, 3])

In [152]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype=np.int16)

In [153]:
b

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [154]:
b.ndim

2

In [155]:
a.ndim

1

In [156]:
a.shape

(3,)

In [157]:
b.shape

(2, 3)

In [158]:
a.dtype

dtype('int64')

In [159]:
b.dtype

dtype('int16')

Attribute	Meaning

**itemsize**	Size of one element in bytes

**size**	Total number of elements

**nbytes**	Total memory occupied (size * itemsize)


In [160]:
a.itemsize

8

In [161]:
a.size

3

In [162]:
a.nbytes

24

Accesing / Changing rows and columns

In [163]:
np1 = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [164]:
np1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [165]:
# Getting specific element [r, c]
np1[1, 5]

13

In [166]:
# using Negavtive indexing
np1[1, -2]

13

In [167]:
# Getting specifc row
np1[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [168]:
np1[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [169]:
# Getting specific columns
np1[:, 5]

array([ 6, 13])

In [170]:
np1[:, 4]

array([ 5, 12])

In [171]:
# Accesing using [start : stop : step]
np1[1, 2:5]

array([10, 11, 12])

In [172]:
np1[1, 1:7:2]

array([ 9, 11, 13])

In [173]:
np1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [174]:
# Changing elements
np1[0, 4] = 551

In [175]:
np1

array([[  1,   2,   3,   4, 551,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14]])

In [176]:
np1[:, 1] = 5

In [177]:
np1

array([[  1,   5,   3,   4, 551,   6,   7],
       [  8,   5,  10,  11,  12,  13,  14]])

In [178]:
np1[:, 1] = [2, 9]

In [179]:
np1

array([[  1,   2,   3,   4, 551,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14]])

3-D Array

In [180]:
d3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [181]:
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [182]:
d3.ndim

3

In [183]:
d3.shape

(2, 3, 3)

In [184]:
d3[0, 2, 1]

8

In [185]:
# d3[ All Matrix : First row of each matrix : All Column]

d3[:, 1]

array([[ 4,  5,  6],
       [13, 14, 15]])

In [186]:
# d3[All Matrix : First row of each matrix : First Column of Matrix]

d3[:, 1, 1]

array([ 5, 14])

In [187]:
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [188]:
d3[1, 0, :] = [10, 11, 12]

In [189]:
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [190]:
d3[1, 1:3, :] = [[0, 0, 0], [0, 0, 0]]

In [191]:
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [ 0,  0,  0],
        [ 0,  0,  0]]])

In [192]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [193]:
np.ones([4,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [194]:
np.full([2, 2], 551)

array([[551, 551],
       [551, 551]])

In [195]:
nn = np.full(a, 66)
nn

array([[[66, 66, 66],
        [66, 66, 66]]])

In [196]:
# Any other number (full like / to make same matrix)

n = np.full_like(np1, 5)

In [197]:
n

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [198]:
np.random.rand(2, 3)

array([[0.15088091, 0.36086276, 0.62049567],
       [0.14207144, 0.17116196, 0.47095373]])

In [199]:
# randint( takes number below it (low) , size = (r, c))

np.random.randint(2, size=(3, 3))

array([[1, 0, 1],
       [1, 1, 1],
       [1, 1, 0]])

In [200]:
# randint( takes number btw (low and hight) , size = (r, c))

np.random.randint(2, 5, size=(3, 3))

array([[3, 2, 4],
       [4, 2, 3],
       [2, 2, 4]])

In [201]:
identity_matrixs = np.identity(5)

In [202]:
identity_matrixs

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [203]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)

In [204]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [205]:
output = np.ones([5, 5])
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [206]:
z = np.zeros([3, 3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [207]:
z[1, 1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [208]:
output[1:4, 1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [209]:
m = np.array([1, 2, 3, 4])

In [210]:
m

array([1, 2, 3, 4])

In [211]:
m + 2

array([3, 4, 5, 6])

In [212]:
m - 2

array([-1,  0,  1,  2])

In [213]:
m * 2

array([2, 4, 6, 8])

In [214]:
m / 2

array([0.5, 1. , 1.5, 2. ])

In [215]:
m1 = np.array([1, 2, 3, 4])

In [216]:
m + m1

array([2, 4, 6, 8])

In [217]:
m1 ** 2

array([ 1,  4,  9, 16])

In [218]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [219]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [220]:
m1 + m

array([2, 4, 6, 8])

In [221]:
x = np.ones((2, 3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [222]:
y = np.full((3, 2), 2)
y

array([[2, 2],
       [2, 2],
       [2, 2]])

In [223]:
np.matmul(x, y)

array([[6., 6.],
       [6., 6.]])

**Statistics**

In [224]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
stats.min()

1

In [226]:
stats.max()

6

In [227]:
np.max(stats, axis=1)

array([3, 6])

In [228]:
np.min(stats, axis=1)

array([1, 4])

In [229]:
np.sum(stats, axis=0)

array([5, 7, 9])

**Reorganizing Arrays**

In [230]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [231]:
# after = before.reshape(8, 1)
# after

In [232]:
after = before.reshape(4, 2)
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

**Vertical stacking**

In [233]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

In [234]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [235]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

In [236]:
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [237]:
data = np.genfromtxt('/content/data.txt', delimiter=',')

In [238]:
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

data = data.astype('int32')
data

In [239]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [240]:
data[data > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [241]:
data[ data%2 == 0]

array([196.,   4.,  34.,   6.,   8.,   0.,   2.,   4.,  42.,  12., 766.,
         4.,   6.,   4.,   4.,   6.,   0.,  12.,  22.,   2.,  78.,   0.,
         2.,   8.,  76.,  88.])

In [242]:
data1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

data1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [243]:
data1[[0, 2, 4, 6]]

array([1, 3, 5, 7])

In [244]:
data

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [245]:
np.all(data > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [246]:
data[(data > 50) & (data < 100)]

array([75., 75., 55., 78., 76., 88.])

In [247]:
(data > 50) & (data < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [248]:
(~(data > 50) & (data < 100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [249]:
p = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25], [26, 27, 28, 29, 30]])

In [250]:
p

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [251]:
p[0:4, 1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [252]:
p[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [253]:
p[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [254]:
p[2:4, 0:2]

array([[11, 12],
       [16, 17]])